
flex: 0
top_n: 3 # doesn work for normal matching
# how many options you wanna see (desceding order in terms of closeness)
# 0 for toe to toe; 1 for flexible matching

output_path: "output.xlsx"

########################################################  input file   ###########################################################################

# input file 
input_file : "fileexample.xlsx"

## the categories (sku name, optional) to be considered 
file_cols: ["cate1", "cate2", "cate3", "cate4", "sku_name"] # 1. always put the sku_name at the end 2. make sure it's ascedning order

## to what level we wanna do matching: category level, including sku_name?
consider_sku_name: 1 # 1 consider sku name, 0 not to consider
sku_cate_num: 4

## do translation? (work for non english data)
trans_file: 0 # 0 for no, 1 for yes
trans_file_path: "date_file_translation.joblib"

######################################################## target file   ###########################################################################

# target file
# the one we wanna do matching
target_file : "cate.xlsx"
cate_cols: ['cate1', 'cate2', 'cate3'] 

## to what level of the target: category level
cate_main_num: 3

## do translation? (work for non english data)
trans_cate: 0 # 0 for no, 1 for yes
trans_cate_path: "date_cate_translation.joblib"

